server:
  port: 8888

github:
  client:
    id: 1675dfd6e33f18f16d6b
    secret: 59387f1078a32db421accba299f0d817a03916f5
  redirect:
    url: http://localhost:8888/callback
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/community?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver