server:
  port: 8888


github:
  client:
    id: 1675dfd6e33f18f16d6b
    secret: 59387f1078a32db421accba299f0d817a03916f5
  redirect:
    url: http://localhost:8888/callback
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/community?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    datasource:
      type: com.alibaba.druid.pool.DruidDataSource
#  thymeleaf:
#    prefix: classpath:/templates/
#    suffix: .html
#    encoding: utf-8
#    mode: LEGACYHTML5
#    cache: false
#  mvc:
#    static-path-pattern: /**
#  resources:
#    static-locations: classpath:/static/

mybatis:
  configuration:
    map-underscore-to-camel-case: true
  type-aliases-package: com.ch.community.mapper
  mapper-locations: classpath:mapper/*.xml
ucloud:
  ufile:
    public-key: TOKEN_80d0fa6f-6734-4e31-9730-982300c4d4ad
    private-key: 1c7b095b-0921-43ca-ac7a-f33c1158ed3b